export const SEARCH_GENRES = "SEARCH_GENRES";
export const CLEAR_GENRES = "CLEAR_GENRES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
// export const SEARCH_GENRES = "SEARCH_GENRES";
// export const SEARCH_GENRES = "SEARCH_GENRES";
